version: 0.1
phases:
  install:
    commands:
    - npm install -g @angular/cli
  build:
    commands:
    - echo Installing source NPM dependencies...
    - npm install
    - echo Build started on `date`
    -ng build --prod --configuration=${BUILD_ENV}
  post_build:
    commands:
    - aws s3 cp dist s3://{S3_BUCKET} --recursive
    -aws configure set preview.cloudfront true
    -echo ${CLOUDFRONT_DISTRIBUTION_ID}
    -echo ${BUILD_ENV}
    -echo ${S3_BUCKET}
    -aws cloudfront create-invaildation --distribution_id ${CLOUDFRONT_DISTRIBUTION_ID} --paths '/*'
artifacts:
  files:
  - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
